/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import connection.CRUD;
import java.io.IOException;
import javax.swing.JOptionPane;
import modelos.Vendedor;

/**
 *
 * @author Bruno
 */
public class CadastroView extends javax.swing.JFrame {

    private HomeView h;

    /**
     * Creates new form Cadastro
     */
    public CadastroView(HomeView home) {
        h = home;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeFD = new javax.swing.JTextField();
        usuarioFD = new javax.swing.JTextField();
        senhaFD = new javax.swing.JPasswordField();
        emailFD = new javax.swing.JTextField();
        button = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nomeFD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        nomeFD.setForeground(new java.awt.Color(153, 153, 153));
        nomeFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 255)));
        nomeFD.setOpaque(false);
        nomeFD.setBackground(new java.awt.Color(0,0,0,1));
       
        getContentPane().add(nomeFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 210, 210, -1));

        usuarioFD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usuarioFD.setForeground(new java.awt.Color(153, 153, 153));
        usuarioFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 255)));
        usuarioFD.setOpaque(false);
        usuarioFD.setBackground(new java.awt.Color(0,0,0,1));
      
        getContentPane().add(usuarioFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 270, 210, -1));

        senhaFD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        senhaFD.setForeground(new java.awt.Color(153, 153, 153));
        senhaFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 255)));
        senhaFD.setOpaque(false);
        senhaFD.setBackground(new java.awt.Color(0,0,0,1));
     
        getContentPane().add(senhaFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 390, 210, -1));

        emailFD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        emailFD.setForeground(new java.awt.Color(153, 153, 153));
        emailFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 255)));
        emailFD.setOpaque(false);
        emailFD.setBackground(new java.awt.Color(0,0,0,1));
      
        getContentPane().add(emailFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 210, -1));

        button.setContentAreaFilled(false);
        button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 430, 170, 20));

        fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bruno\\Documents\\NetBeansProjects\\trabalhodejava\\src\\main\\java\\imagens\\ImagemCadastro.png")); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 601));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed
        // TODO add your handling code here:
        try {
            CRUD oi = new CRUD();
            boolean checkIfUsuarioExist = oi.checkIfExist("vendedor", usuarioFD.getText()), checkEmail = true;

            //vendo se o meail está no formato certo
            checkEmail = emailFD.getText().contains("@") && (emailFD.getText().endsWith(".com") || emailFD.getText().endsWith(".br"));

            if (!checkIfUsuarioExist && checkEmail) {
                Vendedor vendedor = new Vendedor(nomeFD.getText(), "3", usuarioFD.getText(), emailFD.getText(), new String(senhaFD.getPassword()));
                oi.add(vendedor);
                dispose();
                JOptionPane.showMessageDialog(this, "Vendedor adicionado com sucesso!", "Cadastro realizado!", HEIGHT);
            } else {
                if (checkIfUsuarioExist) {
                    JOptionPane.showMessageDialog(this, "Usuario já existe.", "Erro no cadastro", HEIGHT);

                } else if (!checkEmail) {
                    JOptionPane.showMessageDialog(this, "Email não corresponde ao formato adequado.", "Erro no cadastro", HEIGHT);

                }
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Algum erro ocorreu, tente novamente.", "Erro no cadastro", JOptionPane.WARNING_MESSAGE);

        }

    }//GEN-LAST:event_buttonActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
                h.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JTextField emailFD;
    private javax.swing.JLabel fundo;
    private javax.swing.JTextField nomeFD;
    private javax.swing.JPasswordField senhaFD;
    private javax.swing.JTextField usuarioFD;
    // End of variables declaration//GEN-END:variables
}
