/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import connection.CRUD;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.ListModel;
import modelos.Produto;
import modelos.Vendas;

/**
 *
 * @author Bruno
 */
public class HistoricoVendasView extends javax.swing.JFrame {

    private clienteHomeView h;

    /**
     * Creates new form Estoque
     */
    public HistoricoVendasView(clienteHomeView home) {
        h = home;

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        homeBTn = new javax.swing.JButton();
        prdVendedor = new javax.swing.JTextField();
        panel = new javax.swing.JScrollPane();
        estoqueList = new javax.swing.JList<>();
        pesquisaFD = new javax.swing.JTextField();
        prdCliente = new javax.swing.JTextField();
        prdID = new javax.swing.JTextField();
        prdDate = new javax.swing.JTextField();
        fundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque - At Home");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        homeBTn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bruno\\Documents\\NetBeansProjects\\trabalhodejava\\src\\main\\java\\imagens\\homeBtn.png")); // NOI18N
        homeBTn.setContentAreaFilled(false);
        homeBTn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBTn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBTnActionPerformed(evt);
            }
        });
        getContentPane().add(homeBTn, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 720, -1, -1));

        prdVendedor.setEditable(false);
        prdVendedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prdVendedor.setForeground(new java.awt.Color(51, 51, 51));
        prdVendedor.setText(Produto.NA);
        prdVendedor.setToolTipText("");
        prdVendedor.setBorder(null);
        prdVendedor.setHorizontalAlignment(JLabel.CENTER);
        prdVendedor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prdVendedor.setOpaque(false);
        pesquisaFD.setBackground(new java.awt.Color(0,0,0,1));
        prdVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prdVendedorActionPerformed(evt);
            }
        });
        getContentPane().add(prdVendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 230, 250, 30));

        panel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        DefaultListModel<Vendas> listModel = new DefaultListModel<>();
        estoqueList.setBackground(new java.awt.Color(28, 28, 36));
        estoqueList.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        estoqueList.setModel(listModel);
        estoqueList.setForeground(new java.awt.Color(255, 255, 255));
        CRUD oi;
        try{
            oi = new CRUD();

            for(Vendas vendas: oi.getTodosVendas()){
                listModel.addElement(vendas);
                System.out.println("try 2");

            }
        }catch(Exception e){
            System.out.println("erro excesão 2");

        }

        DefaultListCellRenderer renderer =  (DefaultListCellRenderer)estoqueList.getCellRenderer();
        renderer.setHorizontalAlignment(JLabel.CENTER);
        estoqueList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                estoqueListMouseClicked(evt);
            }
        });
        panel.setViewportView(estoqueList);

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 166, 290, 510));

        pesquisaFD.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        pesquisaFD.setForeground(new java.awt.Color(51, 51, 51));
        pesquisaFD.setToolTipText("");
        pesquisaFD.setBorder(null);
        pesquisaFD.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pesquisaFD.setAlignmentY(JTextField.CENTER);
        pesquisaFD.setHorizontalAlignment(JLabel.CENTER);
        pesquisaFD.setOpaque(false);
        pesquisaFD.setBackground(new java.awt.Color(0,0,0,1));
        pesquisaFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisaFDActionPerformed(evt);
            }
        });
        pesquisaFD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pesquisaFDKeyTyped(evt);
            }
        });
        getContentPane().add(pesquisaFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 105, 160, -1));

        prdCliente.setEditable(false);
        prdCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prdCliente.setForeground(new java.awt.Color(51, 51, 51));
        prdCliente.setText(Produto.NA);
        prdCliente.setToolTipText("");
        prdCliente.setBorder(null);
        prdCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prdCliente.setHorizontalAlignment(JLabel.CENTER);
        prdCliente.setOpaque(false);
        prdCliente.setBackground(new java.awt.Color(0,0,0,1));
        getContentPane().add(prdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 260, 30));

        prdID.setEditable(false);
        prdID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prdID.setForeground(new java.awt.Color(51, 51, 51));
        prdID.setText(Produto.NA);
        prdID.setToolTipText("");
        prdID.setBorder(null);
        prdID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prdID.setHorizontalAlignment(JLabel.CENTER);
        prdID.setOpaque(false);
        prdID.setBackground(new java.awt.Color(0,0,0,1));
        getContentPane().add(prdID, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 260, 40));

        prdDate.setEditable(false);
        prdDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        prdDate.setForeground(new java.awt.Color(51, 51, 51));
        prdDate.setText(Produto.NA);
        prdDate.setToolTipText("");
        prdDate.setBorder(null);
        prdDate.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        prdDate.setHorizontalAlignment(JLabel.CENTER);
        prdDate.setOpaque(false);
        prdDate.setBackground(new java.awt.Color(0,0,0,1));
        getContentPane().add(prdDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 260, 30));

        fundo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Bruno\\Documents\\NetBeansProjects\\trabalhodejava\\src\\main\\java\\imagens\\telas1.png")); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        h.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void pesquisaFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisaFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisaFDActionPerformed

    private void prdVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prdVendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prdVendedorActionPerformed

    private void estoqueListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_estoqueListMouseClicked
        // TODO add your handling code here:
        Vendas p = estoqueList.getSelectedValue();
        prdVendedor.setText(p.getVendedor_id());
        prdCliente.setText(p.getCliente_id());
        prdID.setText(p.getId());
        prdDate.setText(p.getTimestamp().toString());


    }//GEN-LAST:event_estoqueListMouseClicked

    private void pesquisaFDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesquisaFDKeyTyped
        // TODO add your handling code here:

        atualizarEstoqueList(pesquisaFD.getText());

    }//GEN-LAST:event_pesquisaFDKeyTyped

    private void homeBTnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBTnActionPerformed
        // TODO add your handling code here:
        dispose();
        h.setVisible(true);
    }//GEN-LAST:event_homeBTnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        limparLista();
    }// GEN-LAST:event_editBtnActionPerformed

    private void limparLista() {
        estoqueList.clearSelection();
    }

    protected void atualizarEstoqueList(String nome) {
        DefaultListModel<Produto> Model = (DefaultListModel) estoqueList.getModel();
        CRUD oi;
        try {
            oi = new CRUD();
            Model.clear();
            for (Produto produto : oi.getTodosProdutos(nome)) {
                Model.addElement(produto);
                System.out.println("try 2");

            }
            Vendas p = estoqueList.getModel().getElementAt(1);

            prdVendedor.setText(p.getVendedor_id());
            prdCliente.setText(p.getCliente_id());
            prdID.setText(p.getId());
            prdDate.setText(p.getTimestamp().toString());

        } catch (Exception e) {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HistoricoVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HistoricoVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HistoricoVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HistoricoVendasView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HistoricoVendasView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Vendas> estoqueList;
    private javax.swing.JLabel fundo;
    private javax.swing.JButton homeBTn;
    private javax.swing.JScrollPane panel;
    private javax.swing.JTextField pesquisaFD;
    private javax.swing.JTextField prdCliente;
    private javax.swing.JTextField prdDate;
    private javax.swing.JTextField prdID;
    private javax.swing.JTextField prdVendedor;
    // End of variables declaration//GEN-END:variables
}
