/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Telas;

import java.awt.Component;
import modelos.Images;
/**
 *
 * @author Bruno
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        home = new javax.swing.JDialog();
        fotoperfil = new javax.swing.JLabel();
        nomeUsuario = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        fundoHome = new javax.swing.JLabel();
        usuarioFD = new javax.swing.JTextField();
        senhaFD = new javax.swing.JPasswordField();
        button = new javax.swing.JButton();
        fundo = new javax.swing.JLabel();

        home.setMinimumSize(new java.awt.Dimension(220, 607));
        home.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fotoperfil.setIcon(new javax.swing.ImageIcon("src\\main\\java\\imagens\\panda-home.png")); // NOI18N
        Images img = new Images();
        fotoperfil.setIcon(img.scalar(fotoperfil, 175, 187));
        fotoperfil.setMinimumSize(new java.awt.Dimension(100, 100));
        fotoperfil.setPreferredSize(new java.awt.Dimension(187, 196));
        home.getContentPane().add(fotoperfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 23, 193, 187));

        nomeUsuario.setEditable(false);
        nomeUsuario.setColumns(10);
        nomeUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nomeUsuario.setRows(1);
        nomeUsuario.setText("xxxxxxxxxxxxxxxxxxx");
        nomeUsuario.setAlignmentX(Component.CENTER_ALIGNMENT);
        nomeUsuario.setAlignmentY(Component.CENTER_ALIGNMENT);
        home.getContentPane().add(nomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        fundoHome.setIcon(new javax.swing.ImageIcon("src\\main\\java\\imagens\\fundohome.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fundoHome)
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fundoHome, javax.swing.GroupLayout.PREFERRED_SIZE, 607, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        home.getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 1, -1, 610));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        usuarioFD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        usuarioFD.setForeground(new java.awt.Color(51, 51, 51));
        usuarioFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 255)));
        usuarioFD.setOpaque(false);
        usuarioFD.setBackground(new java.awt.Color(0,0,0,1));
        usuarioFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioFDActionPerformed(evt);
            }
        });
        getContentPane().add(usuarioFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, 210, -1));

        senhaFD.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        senhaFD.setForeground(new java.awt.Color(51, 51, 51));
        senhaFD.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(204, 204, 255)));
        senhaFD.setOpaque(false);
        senhaFD.setBackground(new java.awt.Color(0,0,0,1));
        senhaFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFDActionPerformed(evt);
            }
        });
        getContentPane().add(senhaFD, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 210, -1));

        button.setContentAreaFilled(false);
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, 170, 20));

        fundo.setIcon(new javax.swing.ImageIcon("src\\main\\java\\imagens\\ImagemLogin.png")); // NOI18N
        getContentPane().add(fundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usuarioFDActionPerformed

    private void senhaFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFDActionPerformed

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed

    }//GEN-LAST:event_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JLabel fotoperfil;
    private javax.swing.JLabel fundo;
    private javax.swing.JLabel fundoHome;
    private javax.swing.JDialog home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextArea nomeUsuario;
    private javax.swing.JPasswordField senhaFD;
    private javax.swing.JTextField usuarioFD;
    // End of variables declaration//GEN-END:variables
}
